### ISSUE TITLE
Hardware wallet default language

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet#124] opened 2019-03-11 16:51 UTC
**Describe the bug**
If empty string is passed as a call to `ApplySettings` use `English` as default instead of showing empty

![2019-03-11 22 21 54](https://user-images.githubusercontent.com/8619106/54141721-380ba000-444c-11e9-96af-e76e255cf112.jpg)

**Environment information:**
- Any

**Steps to Reproduce**
use js or go lib and call `ApplySettings` with language as `""`

**Actual behavior**
Shows empty string

**Expected behavior**
Show default language

**Comment by olemis** [comment] 2019-03-14 16:16
should be fixed as a side effect for completing skycoin/hardware-wallet-js#59 .

**Comment by olemis** [comment] 2019-03-14 17:16
fixed in 4a00e78

**Closed by olemis** 2019-03-14 17:16 UTC
Labels: Milestone v.1.0.0, bug, stdev, wip

**Comment by Senyoret1** [comment] 2019-03-17 19:14
@olemis , apparently the problem is still present.

**Comment by stdevIvr** [comment] 2019-03-18 02:33
@Senyoret1 I just tested it and it works. Are you on `develop` branch? Is it the latest commit??

**Comment by olemis** [comment] 2019-03-18 15:33
> @Senyoret1 I just tested it and it works. Are you on `develop` branch? Is it the latest commit??

same with the emulator ... will test in the device later today .

**Comment by Senyoret1** [comment] 2019-03-18 15:43
@stdevIvr I think you are right, the change was made to solve what was originally posted. I was thinking more about what I was talking about in https://github.com/skycoin/hardware-wallet-js/pull/62#pullrequestreview-214528018 . I created a new issue with the details: https://github.com/skycoin/hardware-wallet/issues/135
