### ISSUE TITLE
Test new graphic assets on device

### ISSUE THREAD

**Issue by jdknives** [skycoin/hardware-wallet#125] opened 2019-03-11 17:14 UTC
We need to load the new Sky logos and action icons on the Skywallet and check their look on the device itself. Pictures of all the icons are required.

**Comment by olemis** [comment] 2019-03-13 19:01
this is a duplicate of #17

**Comment by olemis** [comment] 2019-04-16 17:04
fixed in 0813cd5

**Closed by olemis** 2019-04-16 17:04 UTC
Labels: Milestone v.1.0.0, bootloader, firmware, good first issue, stdev, wip
